title: Danilo Parra Jr.
email: daniloparrajr.work@gmail.com
description: Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

linkedin_username: daniloparrajr
github_username:  daniloparrajr
stackoverflow_username:  danilo-jr-parra

collections:
  projects:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include: ['_pages']

exclude:
  - package.json
  - package-lock.json
  - webpack.config.js
  - postcss.config.js

compress_html:
  clippings: all